import "../styles/globals.css";
import "../styles/Sidebar.scss";
import { useEffect } from "react";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Layout } from "../components";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Stackoverflow clone</title>
        <meta
          name="stackoverflow clone"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout Component={Component} pageProps={pageProps} />
    </>
  );
}

export default MyApp;
